# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text=b'1920x1080', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(),
        ),
    ]
