# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text=b'1600x1000', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
