# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('blog', '0004_auto_20170718_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text=b'800x600', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
