# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0004_auto_20170421_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='profile_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=models.TextField(default='About me'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background',
            field=models.ForeignKey(blank=True, help_text='1920x1080', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.TextField(default='Ecommerce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.TextField(default='eccomerce'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='600x600', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
